name: Snyk Codescan
description: |
    Use Snyk service to scan the code of this repository.
    Be sure to check-out the code prior to using this action.

inputs:
  aws-region:
    description: You know
    default: us-east-2
    type: string
    required: false

  role-to-assume:
    description: The AWS role to pick up permissions of. Note that you don't need AWS access keys for this, because it's approved by the role trust policy. Possibly stored in vars.AWS_GA_ROLE_ARN_PROD
    required: true
    default: arn:aws:iam::653832775139:role/github-actions-role
    type: string

  aws-access-key-id:
    description: if you're connecting to AWS via access key IDs
    required: false
    type: string
    default: ""
  aws-secret-access-key:
    description: if you're connecting to AWS via access key IDs
    required: false
    type: string

#secrets:
# We can't pass secrets to a composite action, only a called workflow.

runs:
  using: composite
  #env:
  #  GITHUB_SHA: ${{ fromJson(inputs.vars).GITHUB_SHA }}

  steps:
  - name: Configure AWS credentials
    if: ${{ inputs.aws-access-key-id == '' }}
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      aws-region: ${{ inputs.aws-region }}

  - name: Configure AWS credentials
    if: ${{ inputs.aws-access-key-id != '' }}
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      aws-region: ${{ inputs.aws-region }}
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2

